package com.example.emrtdapplication.constants

object FacialInformationConstants {
    const val FACIAL_INFORMATION_SIZE = 20
    const val FACIAL_INFORMATION_SIZE_STRING = "Size of Facial Information must be ${FACIAL_INFORMATION_SIZE}!"
    const val FACIAL_INFORMATION_IMAGE_BLOCK_LENGTH_INDEX_1 = 0
    const val FACIAL_INFORMATION_IMAGE_BLOCK_LENGTH_INDEX_2 = 1
    const val FACIAL_INFORMATION_IMAGE_BLOCK_LENGTH_INDEX_3 = 2
    const val FACIAL_INFORMATION_IMAGE_BLOCK_LENGTH_INDEX_4 = 3
    const val FACIAL_INFORMATION_FEATURE_POINTS_INDEX_1 = 4
    const val FACIAL_INFORMATION_FEATURE_POINTS_INDEX_2 = 5
    const val FACIAL_INFORMATION_GENDER_INDEX = 6
    const val FACIAL_INFORMATION_EYE_COLOR_INDEX = 7
    const val FACIAL_INFORMATION_HAIR_COLOR_INDEX = 8
    const val FACIAL_INFORMATION_FEATURE_MASK_INDEX_1 = 9
    const val FACIAL_INFORMATION_FEATURE_MASK_INDEX_2 = 10
    const val FACIAL_INFORMATION_FEATURE_MASK_INDEX_3 = 11
    const val FACIAL_INFORMATION_EXPRESSION_HIGH_BYTE = 12
    const val FACIAL_INFORMATION_EXPRESSION_LOW_BYTE = 13
    const val FACIAL_INFORMATION_POSE_ANGLE_START_INDEX = 14
    const val FACIAL_INFORMATION_POSE_ANGLE_END_INDEX = 16
    const val FACIAL_INFORMATION_POSE_ANGLE_UNCERTAINTY_START_INDEX = 17
    const val FACIAL_INFORMATION_POSE_ANGLE_UNCERTAINTY_END_INDEX = 19
}